github-dark.css
=> Changed the 'private' tags to black

github-dark.css
Before : ![Imgur](http://i.imgur.com/tzhZSpj.png)
After : ![Imgur](http://i.imgur.com/HyevUz1.png)
=> Fix typo in class name for yellow flash message

github-dark.css
In the notification panel, all PRs are seen in purple, even if they've got different states.
This quick fix resolves this.
=> Fix pull request icon color

github-dark.css
This fixes the "committed for" part of the author section of commits and commit teases, which appears when the committer is not the author.
Example: https://github.com/vim-scripts/taglist.vim
=> Commit: fix "committed for" in author section

github-dark.css
The commit meta are shown with a white background (at least on Github enterprise).
=> Darkerize commit meta

github-dark.css
As indicated at https://github.com/blog/2085-a-new-look-for-repositories, a new look for respositories is coming.  Some CSS has changed for the active tab, so this PR updates the CSS to apply the necessary styles for the new CSS.
=> Update for new GitHub Repository View

github-dark.css
The `.repository-description` class no longer exists in the new look, and is also not styled by GitHub in the old look.
=> New repos: Fix repository meta/description

github-dark.css
This tiny snippet darkens both horizontal and vertical scroll bars of github.com on web browsers such as Safari, Google Chrome and Opera except for Firefox.  (Strictly speaking, Google Chrome no longer uses the WebKit engine, but `::-web-kit-scrollbar**` still works on the latest Google Chrome.)
=> Darken scroll bars for WebKit-based browsers (Safari, Google Chrome, etc.)

github-dark.css
Example: https://github.com/bitcoin/bips/blob/master/bip-0037.mediawiki
Before:
After:
=> MediaWiki: Apply background-color to the TOC

github-dark.css
I forgot to include `::-webkit-scrollbar-corner` selector in my last pull request (#272), which has already been committed to the master branch. So I am putting this separate pull request to add it. Without this selector, the bottom right corner (the intersection of the horizontal and vertical scroll bars), which appears only when both scroll bars are active like when Octotree sidebar is opened, does not turn dark gray and remains white. Sorry, I should have tested more thoroughly.
=> darken webkit scrollbar corners

github-dark.css
This makes sure the horizontal scrollbar can not be any taller than 10 pixels
Previously the horizontal scrollbar looked a little large:
This makes it a little shorter:
=> Constrict the horizontal scrollbar height

github-dark.css
I wasn't sure how to style this element. It normally has a background gradient:
```css
background-image: linear-gradient(180deg, rgba(255,255,255,0) 60%, #fff),linear-gradient(70deg, #e0f1ff 32%, #fffae3)
```
I tried yellow but it didn't look right, and I took a look at the various gradients that already exist, but those didn't look good either, so I stuck with blue. Let me know what you think. You can find the unstyled element if you go to the main GitHub page after signing in (not your profile page). It's the page that shows your news feed.
=> Issues: style intro-shelf

github-dark.css
fix the bias of comment emoji reaction
before
after
=> fix emoji bias

.github/ISSUE_TEMPLATE.md
Without the leading hyphen, these checkboxes are rendered as plaintext.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stylishthemes/github-dark/322)
=> Fix checklist rendering in issue template

github-dark.css
Essentially this, before and after below
=> User profile tabs: add base-color top border on selected tab

github-dark.css
This fixes consistency with other rss icon colors
Before and after
=> enhancement: add https://github.com/ bottom page rss icon to orange style

github-dark.css
@Mottie this looks good but not so bright that it pierces corneas
in other places slightly too dark on the dull side, check it.
=> not too bright (my corneas cried for help) not too dark

github-dark.css
Hi,
this merge request fixes some minor issues.
It was created with help of [Feram][repo].
If it helped to improve this repository,
please consider to [star Feram's repo][repo] to show some love! 😊
PS:
The [Feram team][feramhq] is currently working on making this technology
available for everyone. If you want to be one of the first to use it,
please sign up up for the newsletter on [feram.co].
[repo]: https://github.com/feramhq/feram
[feramhq]: https://github.com/feramhq
[feram.co]: http://feram.co
=> Minor fixes

github-dark.css
Fixes the table row background for `.failed` and `.refunded` rows within
the `.payment-history` table available on https://github.com/settings/billing
before:
after:
=> fix background in payments for failed/refunded txn

themes/codemirror/monokai-spacegray-eighties.css, themes/github/monokai-spacegray-eighties.css, themes/jupyter/monokai-spacegray-eighties.css
tmTheme source:
https://github.com/pyoio/monokai-spacegray
It seems GitHub doesn't apply separate css classes some elements that it should and so the theme, unfortunately, isn't exactly like it appears in Sublime but it's close enough.
Only tested the appearance with Python, javascript and xml files but I think it should look fine with other languages on GitHub.
=> Added Monokai - Spacegray Eighties theme from Sublime Text

github-dark.css
Child images of `event-created` id added to CSS filters.  Resolves #434.
Note: Github itself seems to have a CSS bug for the first issue image/text where the image overlaps the text.  Apparent even with Github-Dark switched off.
=> Added CSS selector to cover "event-created" id

github-dark.css
The selector `.dashboard-notice` from [this line of github-dark.css](https://github.com/StylishThemes/GitHub-Dark/blob/ed28c8852ab10bbad1f7b0fb375dbadce52d92e6/github-dark.css#L1693) applying the rule `color: #c0c0c0 !important;`
Had been overpowered by
[this stock stylesheet](https://assets-cdn.github.com/assets/github-6a628757f656425789b747aa37ffe446cad8faaa6e1217ddc024f3969bddbca7.css)
```css
.dashboard-notice h2 {
margin-top:9px;
margin-bottom:16px;
font-size:18px;
font-weight:normal;
color:#000
}
```
https://assets-cdn.github.com/assets/github-6a628757f656425789b747aa37ffe446cad8faaa6e1217ddc024f3969bddbca7.css
=> Fixed missed .dashboard-notice h2

themes/src/github/github-dark.css
The markup headings were too dark.
Closes #500.
=> Change color in GitHub Dark

github-dark.css
Before:
After
Before:
After:
- The colored text in the "this issue is blocked by" doesn't actually change between the before and after - that's just me switching from a red theme to a blue theme
- Something strange is happening with https://user-images.githubusercontent.com/3282350/27267371-e0aace98-5475-11e7-8b2f-dc774eaf5fd3.png (<img src="https://user-images.githubusercontent.com/3282350/27267371-e0aace98-5475-11e7-8b2f-dc774eaf5fd3.png">). It should turn that icon in the depency-selector item white when the item is active, but for me in situ it's rendering as black. The documentation asks for attachment links, but it might be best to encode it
- it's possible `.zhc-selection-item--is-active` in line 2704 is made unnecessary by the new necessary …
=> Zenhub improvements, mostly for dependencies

github-dark.css
I'm not sure if it's due to the version of GitHub Enterprise I'm using, but code line links don't use the appropriate background-color due to a mismatch in the element-level style being applied (too bad github isn't doing this with a css class!).  This patch resolves that issue.
=> Support GitHub Enterprise highlight

github-dark.css
=> Fix highlighted

github-dark.css
GitHub now has a community forum on https://github.community/.
The regex was a bit too eager to style things outside of github.com.
=> Avoid styling github.community

.github/CONTRIBUTING.md
Old link. Redirected to `Indentation_style` and `#K.26R_style` is now just `#K.26R`.
=> fixed link to K&R style

github-dark.css
=> polls: fix probot polls

github-dark.css
@xt0rted can rest easily now :smiley_cat: 
2px
default 1px
Are you happy with that?
Another alternative is making it lighter instead, but IDK, lets see what comments come of this.
default css points to 1px
```css
.markdown-body kbd {
display: inline-block;
padding: 3px 5px;
font-size: 11px;
line-height: 10px;
color: #444d56;
vertical-align: middle;
background-color: #fafbfc;
border: solid 1px #c6cbd1;
border-bottom-color: #959da5;
border-radius: 3px;
box-shadow: inset 0 -1px 0 #959da5;
}
```
=> kbd: increase inset bottom box-shadow by 1px fixes #629

github-dark.css
max-width is wrong here see
width is correct and jump-to is in right position.
@Mottie did you not see my fix in userCSS? lol
@xt0rted see what I mean? Its bad enough that long titles are cut off but as is you get to see even less 
max, pff, like Pepsi, gimme Coke.
=> issues: really fix #647 and prevent jump to from shifting to left.

github-dark.css
The pre clearly will come into use with some more specific msg later, see issue ticket for before fix looks.
this styles the banner and pre since the .prereceive-feedback-heading` is already handled by autogenerate.
https://github.com/StylishThemes/GitHub-Dark/blob/8313559707f85deb49829f033eecc0f5e554fb76/github-dark.css#L990
=> fix: prereceive feedback banner fixes #658

github-dark.css
I think the blue color may look more natural than the brown, which just looks out-of-place.
Im sure there must be some very good reason to why GitHub-Dark chose to address issues caused by refined GitHub well off default design choices that are not part of default GitHub stylesheet.
But since that was the case, I propose a more suitable color that is actually present around comments, like the blue.
Idk if a border is needed and definitely can be tested as soon as this is triggered.
=> re-tweak: issue #603 and move to grey bg fixes #665

github-dark.css
Test these out @tambry 
gif shows initially zoom at 100% and each full scroll into oposite direction increases 10% zoom up to 130% zoom with no gaps.
Browser FF 61.0
zoom 100% initial scroll to bottom
zoom 110% scroll to top
zoom 120% scroll to bottom
zoom 130% scroll to top
the gif is 15MB (squeezed from original 37MB) so download it...
https://www.dropbox.com/s/5pypt47ab9albi6/treeview.gif?dl=1
=> issues: tree view fixes re: #679

github-dark.css
I imagine at some stage GiHub updated this color from `#eee` to `#ebedf0`which resulted in this break.
=> fix contrib-legend #ebedf0 style

github-dark.css
fixes the broken box-shadow and re-colors to base-color.
=> issues: fix dragover box-shadow and set to base-color instead of green

github-dark.css
Actually this just fixes the color the border is doing my nut in.
https://help.github.com/ the version dropdown menu
see comment in https://github.com/StylishThemes/GitHub-Dark/commit/17c086a6d0b0c491dc6d034f4304c23afc6aac89#commitcomment-29918150
before (this is autogenerated atm)
after
How to add a line around that arrow is the question.
=> fix: dropdown-menu arrow color and border

github-dark.user.css
Previously, the scrollbar corner was not addressed by the CSS and appeared pure white. No the colour matches the thumbs.
Here's a comparison of the changes:
Before
After
Do let me know if anything else is required!
=> Add styling for scrollbar corner of code editor

github-dark.user.css
Make ZenHub issue card titles readable when using dark theme.
Before: 
After:
=> Use light text for ZenHub Issue Card Titles

github-dark.css
Noticed the directory icons weren't being properly styled, due to a
missing style. They are now styled to match file and symlink icons.
See the before and after shots.
It's not clear to me if I've patched this in the proper way based on some other commits so if I need to adjust this somewhere else please let me know. Thanks.
=> Add css to properly colorize directory icon

github-dark.css
Heavy user of ZenHub, and loving GitHub-Dark, but a lot of ZenHub's new features required tweaking since they defaulted white.
This is mostly what I've been using personally that I recently cleaned up a bit. I tried to stick with only colours/styles that already existed. However since there were quite a few new big ZenHub features, quite a few new classes had to be added.
The 4 main areas that were changed are:
- A few new button styles
- `Epics` panel
- `Workspace` Switcher/Editor modal styles
- New confirmation modal
=> Add new zenhub styles

github-dark.css
This is in response to https://github.com/StylishThemes/GitHub-Dark/commit/13765606e236ac4051f5d73d4b1b0b8e804aefab#commitcomment-31604759
I've been testing this out on github.com, gist.github.com, and with Octotree enabled. So far things seem good but I'm leaving this open to test it some more (I think there's more selectors that can be removed) and to collect feedback on it.
If we can get Octotree to use the `form-control` class on their inputs then we should be able to remove the selectors for their inputs too.
=> [wip] Testing out simpler input styling

github-dark.css
I ran `npx grunt generate` and then overrode the background color for `.related-issue-item.navigation-focus`. Wanted to make sure this was correct before pushing to master.
I went with `#333` as `#2a2a2a` seemed too dark.
Fixes #802
=> Fix selected related issue background color

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, README.md
Fixed a few spelling and grammatical errors in the following documentation files: 
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- README.md
=> fix: typos in documentation

.github/CONTRIBUTING.md
`npm run authors` doesn't work:
```
$ npm run authors
npm ERR! missing script: authors
```
`grunt authors` seems to do the job:
```
$ grunt authors
build.json not found - using defaults
Running "authors" task
Running "exec:authors" (exec) task
Done.
```
=> Update Contributing.md authors instructions

README.md
I haven't seen any reference to the split Github Overlay Scrollbars repo in the Readme. Seems like it should belong here.
=> Add Overlay-Scrollbars to Readme.md

github-dark.css
Adjusting lock color when creating a private repo, and repo suggestion name color to be more visible ( yeah nobody cares about suggestion names but still :p )
Before : 
After :
=> Adjusting  lock and repo suggestion name color

Gruntfile.js, github-dark.css, github-dark.user.css, package.json
This fixes the usercss generator so it supports multiple `@-moz-document` rules which is currently being used for the payment iframes, and will also be used to style some of the actions editor.
The second commit shows what was missing by not supporting this.
=> Fix usercss generator so it supports multiple document rules

github-dark.css, tools/generate.js
PRing for some feedback. This fixes the blue links on the [new pricing page](https://github.com/pricing), but seems to break some of them elsewhere such as on https://github.com/features. The issue is they're using `box-shadow` on `:hover` which is being overridden in another rule. Any ideas on what we should do to handle these?
=> Add generate rule for text-blue-mktg

github-dark.css
Currently, `.octotree-sidebar.octotree-github-sidebar .octotree-views .octotree-tree-view .jstree-anchor` has the same CSS specificity as the one from octotree itself, as both are defined using `!important` and with the same number of classes. Thus, which style is selected is not deterministic (GitHub-Dark is selected in Chrome, original Octotree is selected in Firefox).
I notice that all `jstree-anchor` are stored inside `jstree`, thus adding `.jstree` selector will increase specificity (since there are higher number of classes than the original Octotree) and be selected.
This is the issue with Firefox noted in #911
=> Add another class to increase specificity of octotree

github-dark.css
Wanted to PR this to see if someone sees any issues with the change or if it may break something I'm unaware of.
The generated rules are styling `background-color` and `border-color` so this change follows that. It also removes `!important` which was another recent change.
Switching to style just the color removes the left & right border that's showing on the blue section, and the removal of the transparent selector is because it's hiding the border between the breadcrumb section and the blue section. On desktop the breadcrumb section doesn't show on this page, but it does when viewing a [single file](https://github.com/StylishThemes/GitHub-Dark/blob/master/package.json) (the `GitHub-Dark / package.json` text) but there's no border there on desktop.
This is the page used for the …
=> Mobile commit header fixes

package.json
It's my understanding that you don't need to use `npx` when calling Grunt from an npm script. I don't have Grunt installed globally, it's only installed as a dependency in this repo, and using these scripts works perfectly fine for me.
I'm PRing to see what the build server says and for some feedback from @StylishThemes/github to see if anyone has any issues running these.
Task | Command
-- | --
clean | `npm run clean`
generate | `npm run generate`
test | `npm run test` or `npm test`
usercss | `npm run usercss`
We could add more of these in for doing releases, I just wasn't sure what one(s) we'd want right now.
=> Setup npm scripts for common tasks

.github/workflows/main.yml, .travis.yml
Setting fail-fast to false will let each OS run to completion even if one of them fails. This will let us see if an issue is OS specific or not.
=> Use a fail fast build matrix

github-dark.css, github-dark.user.css, tools/usercss-template.css
Fonts like [Fira Code](https://github.com/tonsky/FiraCode#stylistic-sets) and [Inter](https://rsms.me/inter/#features) (the font used by GitHub on their marketing pages) support feature settings. I use Fira Code in my editors and more recently started using on GitHub for consistency. The missing part was being able to turn some of these features on like I can in VSCode. I've been running this change for some time now in its own style with no issues, but I wanted to PR it in case there was something I was missing when adding a new setting to the theme.
The default value is set to `normal` which is the browser default, but if you change it to something like `'ss02', 'ss03', 'ss04'` when using Fira Code you'll notice a difference in how `<=`, `&`, and `$` are displayed.
More info on the …
=> Add support for font-feature-settings on the code font

github-dark.css
In the PR diff view when using the new notifications beta, the toolbar shadow is offset by 133px. With this style it causes the shadow to overlay the diff view.
This fix is equivalent to the fix for issue #1056
fixes #1063
=> fix toolbar shadow offset

tools/usercss-template.css
This is based on the conversation in https://github.com/StylishThemes/GitHub-Dark/pull/1049#discussion_r364920445. I'd like someone else to test this out before it gets merged. In Chrome I didn't see any issues with this change.
=> Remove unneeded quotes from css values

github-dark.css, tools/usercss-template.css
This PR is untested, but the screenshot is taken with a real reproduction via the custom background
=> Fix tinted background color option

github-dark.css
Since this uses `:not()` I wanted to PR it so @silverwind can approve the use of it or tell me how horrible this is 😃
This can be seen under the [Security > Alerts](https://github.com/StylishThemes/GitHub-Dark/network/alerts) section of a repo with an open alert. I'm not sure if it's an issue for all syntax themes, I'm using Monokai here.
Before | After
-- | --
=> Fix code snippet background in security alerts

README.md
The README's link to CONTRIBUTING.md is broken. This PR fixes it
=> readme: fix CONTRIBUTING.md link

github-dark.user.css, index.html, src/main.css, src/template.css, src/vars.css
This lets us fall back to the original GitHub CSS if desired,
but also doesn't rely on generating invalid CSS.
In response to #1193 and #831
=> Use CSS block as value for font-size-choice

github-dark.user.css, src/gen/mappings.js
Hi, this patch will fix the following specificity issue:
|Before|After|
|-------|------|
|![image][1]|![image][2]|
Code in question: `.prose-diff > .markdown-body li ul.added`
Example page: [here][3] (Display the rich content)
I looked into the source code and it seems to me that using `!important` won't cause any conflicts. I also fixed `border-bottom` because some elements remove it entirely.
[1]: https://user-images.githubusercontent.com/18245694/91337952-73cb2e80-e7d4-11ea-8e8c-5bb624c0af43.png
[2]: https://user-images.githubusercontent.com/18245694/91338030-952c1a80-e7d4-11ea-948d-58b52c761b90.png
[3]: https://github.com/hlissner/doom-emacs/pull/3815/files#diff-875e1886e8077a8e8235882e7879d3e2
=> fix: update prose-diff colors for added lines

github-dark.user.css, src/main.css
Since "Trending" tab doesn't have "data-ga" element, it didn't work hover+focus,
so I added a Class that isn't "data-ga".
=> Grant Style to "Trending" Tab

src/vars.css
Previously, certain line numbers on diff views would be indiscernible from their backgrounds. For example…
Before:
After:
=> Add CSS vars for line numbers in diffs

github-custom-fonts.user.css
- Added initial support for [New Code Search and Code View feature preview](https://docs.github.com/en/repositories/working-with-files/managing-files/navigating-files-with-the-new-code-view):
* All text on Code pane
* Symbol name on Symbols pane
Related issue: https://github.com/StylishThemes/GitHub-Dark/issues/1348
=> [Issue #1348] Support New Code Search and Code View feature preview

src/vars.css
This increases some contrast w/r/t some status elements. The effect is more noticeable with text, but I couldn't figure out how to get Firefox to screenshot that.
Before:
After:
Screenshots taken from @the-j0k3r's user page.
=> Add more `--color-attention` vars
