github-dark.css

Added missing selector on Repositories page

---

.stylelintrc
github-dark.css

According to https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#500

Fixed stylelint rules for version 5.

---

github-dark.css

Issues: style explore signup dialog

---

github-dark.css

See #340  
Idk if this is how you guys want it but it works. no idea if thats in right place or if it matters, this is my first ever css anything.
**Before**
**After**
**Unstylled**
This chips away at the long list in #340 the only issue I cant address is the color of the font in box... Ive no idea how.
I think the font in box should remain unaltered no matter what the style of class is, so we dont get yellow font in yellow boxes, brown font in brown boxes etc...
that is with exception of links. Links should always be either base color or the default blueish/underline(onhover) if that makes sense?

Issues: fix .RecentBranches and text pending colors see #340

---

github-dark.css

before and after, please verify.

fix: signed out comment style

---

github-dark.css

darken raw gist view

---

README.md

fuggly town: drawn attention to tag line

---

github-dark.css

IMO this whole block of selectors needs segregating selectively, else some
bits are just too dull, however Im not confident enough to handle this task so Ill simply revert the offending portion.
this is in response to  https://github.com/StylishThemes/GitHub-Dark/pull/358#discussion_r72374077

revert part of #358

---

github-dark.css

status boxes: #message.major add title to white selectors

---

README.md

* update logo link to StylishThemes/logo-/*.svg
* use relative links in readme where possible
* minor section header updates

readme: update logo links and relative link usage also minor header tweaks

---

README.md

readme: relink svg to minified version

---

github-dark.css

fixes #381
textcolor same readable as all other message boxes
@Mottie MottieMottieMottieMottie
sorry about the echo... :grinning:

commnet form error: fix text color  #381

---

github-dark.css

signup button: consistent styling normal + hover is green.

---

github-dark.css

simple cleanup to help readability

rearrage calendar contrib heat section

---

github-dark.css

Fix header color

---

github-dark.css

Fix Octotree sidebar background

---

github-dark.css

Network Graph was left HOT BURNING WHITE AH MY EYES

Fix Network Graph

---

github-dark.css
github-dark.user.css

Fixed Zenhub color issue

---

github-dark.css

Wasn't sure where to place this snippet.
Before
After

fix the CodeMirror-dialog-top (search bar) bottom border

---

github-dark.css

Hi there @stylishthemes crew,
Screenshots should explain.
before
after

fix commit-link inside commit-desc

---

.github/CONTRIBUTING.md

contribution.md: more accurate K&R (KNF variation) link/description

---

github-dark.css

Im not sure if this requires a more targeted selector, but here causes that.
Feedback welcome :)

issues: remove red background fixes #635

---

github-dark.css

bd9d034  works for #638, feel free to tell me if there's another alternative. :stuck_out_tongue_closed_eyes: 
#640 fixes looksee
Edit
<s>I made the hover on close buttons the base color, is that OK?</s>
Not anymore see below/

issues: fixes #638 and fixes #640

---

github-dark.css

fixes: new tag selected text was too dim

---

github-dark.css

Must be logged off and on https://github.com/ to see this page and image.

invert 1clr-code-hosting svg

---

github-dark.css

Fix #668 danger zone button focus loss

---

github-dark.css

issues: add tag-input suggester background fixes #670

---

github-dark.css

issues: fix pr timeline arrow bg

---

github-dark.css

Before:
After:
Default:
Traffic before:
Traffic after:

Fix forks' network tree spacing

---

README.md

moar :heart: the readme has a :heartbeat: 
@silverwind :medal_sports: :1st_place_medal:

README: moar :heart: moar readme :heart: and moar emoji

---

github-dark.css
tools/generate.js

edit:
Visible at `https://github.com/settings/connections/applications/<some-readcted-hash>`

fix: oauth octicon-x color

---

github-dark.css

The change is subtle but here is a before and after  ![prev-next](https://user-images.githubusercontent.com/31389848/43038981-8424aab0-8d1b-11e8-93fd-fa18356ed5f9.gif)

issues: prev-next disabled bg color fixes #708

---

github-dark.css
package.json

ref: comments on #666 
@silverwind @xt0rted

re-tweak #603-#665 .review-comment:target

---

github-dark.css

Realized that I missed some of the reports, this fixes the Cumulative Flow and Release Report pages. Also fix the invite team modal.

Fix zenhub reports

---

github-dark.css

This fixes the header issue (at least in my testing) as well as the toggle button color and footer link color.
[Before](https://user-images.githubusercontent.com/831974/49618176-84df6680-f985-11e8-9811-08dc2e3d65f9.png)
[After](https://user-images.githubusercontent.com/831974/49619320-16e96e00-f98a-11e8-9e0e-32bcabe00deb.png) (toggle button & footer link show hover state)
Fixes #788

Various fixes for octotree

---

github-dark.css

See #814
Sugestions/feedback welcome

fix: bottom border fixes #814

---

github-dark.css

also closes duplicate #813 (already manually closed as dupe)
Suggestions welcome

fix: overdue milestone warning text fixes #765

---

github-dark.css

<s>Ideally this would be going into @silverwind [overlay-scrollbars](https://github.com/silverwind/overlay-scrollbars) repo which would be pushed to StylishThemes.
Usercss is for testing purposes only,</s> 
Edit 18 /01/2019
Now moved to https://github.com/StylishThemes/Overlay-Scrollbars

Remove scrollbars styling fixes #820

---

github-dark.css

see internal discussion
Its important that this doesnt break what already works, I tried adding prefixes but that doesnt apply consistently for this site pages.
Dont merge until we can properly test hence wip label =)

resources site: add initial manual support

---

github-dark.css
tools/generate.js

@silverwind here is a slightly tweaked version which uses more of already existing colors rather than adding new ones.

Green button revamp

---

github-dark.user.css
src/template.css

Currently the font size style is invalid, I don't know whether it's intentional or just a mistake, but it makes sense to make the unit explicit :)

Change font-size-choice to default

---

README.md
github-dark.user.css
src/extensions.css

Would you please "squash and merge"
<h4><details><summary>Image</summary>
</details></h4>
<h4><details><summary>Image</summary>
</details></h4>

Optimize For Sourcegraph

---

src/themes/github/dracula.css

A few adjustments to GitHub Dracula theme that make it look closer to VSCode Dracula theme. Changes are ongoing, I'll remove the draft tag once it's stable.

style(github/dracula): a few adjustments

---

github-dark.user.css
src/extensions.css

Support show-whitespace from refined-github

---

src/main.css
src/vars.css

Commits in this PR:
- Add new native variables (fixes #1320)
- Make links stylized again (fixes #1321)
- Change background of reaction button hover (this was a nagging annoyance that I felt)

Fix the mess that GitHub made
